name: dartstr
repository: https://github.com/kumulynja/dartstr

packages:
  - apps/**
  - packages/**

scripts:
  analyze:
    exec: dart analyze .
  test:selective_unit_test:
    run: melos exec --dir-exists="test" --fail-fast -- dart test
    description: Run dart tests for a specific package in this project.
    packageFilters:
      dirExists: test
  test:
    run: melos run test:selective_unit_test --no-select
    description: Run all dart tests in this project.
