name: nip19
description: This package contains the bech32-encoding for Nostr entities as described in the NIP-19.
version: 0.0.1
repository: https://github.com/kumulynja/dartstr/nip19

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  bech32: ^0.2.2
  nip01: ^0.0.1
  convert: ^3.1.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
