name: nip06
description: This package contains the basic key derivation from mnemonic seed phrase protocol flow for Nostr as described in the NIP-06.
version: 0.0.1
repository: https://github.com/kumulynja/dartstr/tree/main/packages/nip06

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  nip01: ^0.0.2
  bip39: ^1.0.6
  bip32: ^2.0.0
  convert: ^3.1.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
