name: nip26
description: A starting point for Dart libraries or applications.
version: 1.1.1
repository: https://github.com/kumulynja/dartstr/tree/main/packages/nip26

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  bip340: ^0.3.0
  convert: ^3.1.2
  crypto: ^3.0.6
  equatable: ^2.0.5
  nip01: ^0.1.1+2
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
