name: nip01
description: This package contains the basic protocol flows for Nostr as described in the NIP-01.
version: 0.1.1+3
repository: https://github.com/kumulynja/dartstr/tree/main/packages/nip01

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  bip340: ^0.3.0
  dartstr_utils: ^0.0.2
  convert: ^3.1.1
  crypto: ^3.0.3
  web_socket_channel: ^3.0.1
  async: ^2.11.0
  synchronized: ^3.3.0+3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  lints: ^4.0.0
  test: ^1.24.0
