name: nip01
description: This package contains the basic protocol flows for Nostr as described in the NIP-01.
version: 0.1.1+1
repository: https://github.com/kumulynja/dartstr/tree/main/packages/nip01

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  bip340: ^0.3.0
  dartstr_utils: ^0.0.2
  convert: ^3.1.1
  crypto: ^3.0.3
  meta: ^1.15.0
  web_socket_channel: ^3.0.1
  async: ^2.11.0
  synchronized: ^3.3.0+3
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
