name: nip04
description: This package contains the encrypted direct message protocol flow for Nostr as described in the NIP-04.
version: 0.0.2
repository: https://github.com/kumulynja/dartstr/tree/main/packages/nip04

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  convert: ^3.1.1
  dartstr_utils: ^0.0.2
  pointycastle: ^3.9.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  nip01: ^0.1.1
