name: nip04
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/kumulynja/dartstr/nip04

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  convert: ^3.1.1
  dartstr_utils: ^0.0.1
  pointycastle: ^3.9.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  nip01: ^0.0.1
