name: dartstr_utils
description: A library that is part of the dartstr mono-repo to offer some common utilities needed by different Nostr NIPs.
version: 0.0.1
repository: https://github.com/kumulynja/dartstr/tree/main/packages/dartstr_utils

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  convert: ^3.1.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
