name: nip24
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/kumulynja/dartstr/nip24

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  nip01: ^0.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
