targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            nip47_database: lib/src/database/database.dart
            # True to use ISO 8601 strings, false to use Unix timestamps.
            store_date_time_values_as_text: true
      freezed:
        options:
          build_extensions:
            "^lib/{{dir}}/{{file}}.dart": "lib/{{dir}}/generated/{{file}}.freezed.dart"
      source_gen:combining_builder:
        options:
          build_extensions:
            "^lib/{{dir}}/{{file}}.dart": "lib/{{dir}}/generated/{{file}}.g.dart"
