name: nip47
description: This package implements the Nostr Wallet Connect protocol as described in the NIP-47.
version: 0.5.1+3
repository: https://github.com/kumulynja/dartstr/tree/main/packages/nip47

environment:
  sdk: ">=3.7.2 <4.0.0"

# Add regular dependencies here.
dependencies:
  dartstr_utils: ^0.0.2
  nip01: ^0.3.0+1
  nip04: ^0.2.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  drift: ^2.26.1
  sqlite3: ^2.7.5
  bolt11_decoder: ^1.0.2
  decimal: ^2.3.3
  intl: any
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.1
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  lints: ^4.0.0
  test: ^1.24.0
